[package]
name = "FinSc-Fields"
version = "0.1.0"
ipkg = "FinSc-Fields.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Multiset-Transform]
type = "local"
path = "../FinSc-Multiset-Transform"
ipkg = "FinSc-Multiset-Transform.ipkg"

[custom.all.FinSc-Geometry]
type = "local"
path = "../FinSc-Geometry"
ipkg = "FinSc-Geometry.ipkg"
